version: "3.8"

services:
  frontend:
    build:
      context: ./front/dermIa
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./Back
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      - JWT_SECRET_KEY=super-secret-key
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: