services:

  frontend:
    build: ./front/dermia/
    ports:
      - "3000:5173"  
    stdin_open: true
    tty: true


  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dermia
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
